title: Proyectos del curso DWC
description: Mi portafolio de proyectos para el curso de Despliegue de Aplicaciones Web.
repository: hugopc0/Proyectos-del-curso-DWC
theme: jekyll-theme-primer

  # Eliminamos 'remote_theme' y los plugins manuales para usar los que GitHub trae por defecto
